import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Layout } from "@/src/components/layout";
import { fetchProjects } from "./projects/fetchProjects";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { data: projects } = await fetchProjects(1);

  return (
    <html
      lang="en"
      className={inter.variable}
    >
      <body>
        <Layout projects={projects}>{children}</Layout>
      </body>
    </html>
  );
}
