import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppLayout } from "@/src/components/layout/AppLayout";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={inter.variable}
    >
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
